name: Bundlewatch

on:
  pull_request:
  push:

jobs:
  build-pr:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Install dependencies
      run: yarn --frozen-lockfile
      env:
        NODE_AUTH_TOKEN: ${{secrets.TOKEN_REPO}}

    - name: Dev requirements
      run: yarn develop
      env:
        NODE_AUTH_TOKEN: ${{secrets.TOKEN_REPO}}

    - uses: jackyef/bundlewatch-gh-action@0.2.0
      with:
        build-script: yarn run build
        bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
