name: Tests
on: [push]
jobs:
  core:
    runs-on: ubuntu-latest
    name: Tests
    timeout-minutes: 45
    strategy:
      matrix:
        # node-version: [14.x]
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v3

      # node setup
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      # node install
      - run: yarn set version 3.2.3 && yarn --immutable

      - name: Jest tests
        run: yarn test

      # Bundlewatch
      # - run: yarn build
      # - uses: jackyef/bundlewatch-gh-action@master
      #  with:
      #    bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}