# This is a basic workflow to help you get started with Actions
name: Docker build for new volto 16 version

############################################################
#                                                          #
#         TODO: When we can achieve our dreams             #
#                                                          #
#                                                          #
#   1. on pull request review                              #
#   on:                                                    #
#     pull_request_review:                                 #
#       types: [submitted]                                 #
#       branches: [master]                                 #
#                                                          #
#   2. runs if pull request is approved                    #
#   build_develop:                                         #
#     if: github.event.review.state == 'approved'          #
#     steps:                                               #
#       ...                                                #
#                                                          #
############################################################

# Controls when the action will run.
on:
  # Triggers the workflow when a pull request is approved
  # pull_request_review:
  #   types: [submitted]
  #   branches: [master]
  push:
    branches: [upgrade_to_volto16]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_develop:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Runs only if pull request is approved
    # if: github.event.review.state == 'approved'

    # Steps represent a sequence of tasks that will be executed as part of the job
    # Will be run if pull request is approved
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # - name: Merge branch in develop
      #   uses: devmasx/merge-branch@v1.3.1
      #   with:
      #     type: now
      #     label_name: 'In develop'
      #     target_branch: develop
      #     github_token: ${{ github.token }}

      # - name: Switch to develop
      #   uses: actions/checkout@v2
      #   with:
      #     ref: develop

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@4a531fa5a603bab87dfa56578bd82b28508c9547
        uses: docker/build-push-action@v3
        with:
          # List of tags
          tags: redturtletech/io-comune-base:volto16
          # Always attempt to pull a newer version of the image
          pull: true
          # Push is a shorthand for --output=type=registry
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Deploy to rancher
        uses: redturtle/rancher-deploy-action@v0.1.0
        with:
          host: ${{ secrets.RANCHER_HOST }}
          api-username: ${{ secrets.RANCHER_API_USERNAME }}
          api-password: ${{ secrets.RANCHER_API_PASSWORD }}
          cluster-id: ${{ secrets.RANCHER_CLUSTER_ID }}
          project-id: ${{ secrets.RANCHER_PROJECT_ID }}
          namespace: ${{ secrets.RANCHER_NAMESPACE_DEVELOP }}
          workload: ${{ secrets.RANCHER_WORKLOAD_VOLTO16 }}
          image: redturtletech/io-comune-base:volto16
          slack-hook-url: ${{ secrets.RANCHER_SLACK_HOOK_URL }}
