name: Docker build for new volto 16 version

############################################################
#                                                          #
#         TODO: When we can achieve our dreams             #
#                                                          #
#                                                          #
#   1. on pull request review                              #
#   on:                                                    #
#     pull_request_review:                                 #
#       types: [submitted]                                 #
#       branches: [master]                                 #
#                                                          #
#   2. runs if pull request is approved                    #
#   build_develop:                                         #
#     if: github.event.review.state == 'approved'          #
#     steps:                                               #
#       ...                                                #
#                                                          #
############################################################

# Controls when the action will run.
on:
  # Triggers the workflow when a pull request is approved
  # pull_request_review:
  #   types: [submitted]
  #   branches: [master]
  push:
    branches: [upgrade_to_volto16]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Runs only if pull request is approved
    # if: github.event.review.state == 'approved'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          # List of tags
          tags: redturtletech/io-comune-base:volto16
          pull: true
          # Push is a shorthand for --output=type=registry
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Deploy to rancher
        uses: redturtle/rancher-deploy-action@v0.1.0
        with:
          host: ${{ secrets.RANCHER_HOST }}
          api-username: ${{ secrets.RANCHER_API_USERNAME }}
          api-password: ${{ secrets.RANCHER_API_PASSWORD }}
          cluster-id: ${{ secrets.RANCHER_CLUSTER_ID }}
          project-id: ${{ secrets.RANCHER_PROJECT_ID }}
          namespace: ${{ secrets.RANCHER_NAMESPACE_DEVELOP }}
          workload: ${{ secrets.RANCHER_WORKLOAD_VOLTO16 }}
          image: redturtletech/io-comune-base:volto16
          slack-hook-url: ${{ secrets.RANCHER_SLACK_HOOK_URL }}
